// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr58gx9ZcTH8wSEQFbPa6250oRxtGymZQ',
    appId: '1:730851979045:web:4db0f3bd499797fc5974cc',
    messagingSenderId: '730851979045',
    projectId: 'freshproj-276c9',
    authDomain: 'freshproj-276c9.firebaseapp.com',
    storageBucket: 'freshproj-276c9.appspot.com',
    measurementId: 'G-K91EXMY1DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoWieyer-MTRKE3yFQyViQEcKmI58ecCY',
    appId: '1:730851979045:android:a4bf0f956e35e5245974cc',
    messagingSenderId: '730851979045',
    projectId: 'freshproj-276c9',
    storageBucket: 'freshproj-276c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_KGAHmau2lXvXPL0T3x7IeQwHpcscgF0',
    appId: '1:730851979045:ios:79ae79c8413aaa8a5974cc',
    messagingSenderId: '730851979045',
    projectId: 'freshproj-276c9',
    storageBucket: 'freshproj-276c9.appspot.com',
    iosClientId: '730851979045-ff2l77jo53sujrgfotsurqdnmvojtnf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcproj',
  );
}
